2015-11-23 01:01:02 Successed
2015-11-23 02:01:01 Successed
2015-11-23 03:01:01 Successed
2015-11-23 04:01:01 Successed
Traceback (most recent call last):
  File "/home/snowdrop/py/weather.py", line 71, in <module>
    main()
  File "/home/snowdrop/py/weather.py", line 17, in main
    data = json.loads(content)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/home/snowdrop/py/weather.py", line 71, in <module>
    main()
  File "/home/snowdrop/py/weather.py", line 18, in main
    insertIntoDB(data, lt)
  File "/home/snowdrop/py/weather.py", line 53, in insertIntoDB
    values.append(rd['now']['pres'])
KeyError: 'pres'
Traceback (most recent call last):
  File "/home/snowdrop/py/weather.py", line 71, in <module>
    main()
  File "/home/snowdrop/py/weather.py", line 17, in main
    data = json.loads(content)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/home/snowdrop/py/weather.py", line 71, in <module>
    main()
  File "/home/snowdrop/py/weather.py", line 18, in main
    insertIntoDB(data, lt)
  File "/home/snowdrop/py/weather.py", line 53, in insertIntoDB
    values.append(rd['now']['pres'])
KeyError: 'pres'
